name: Setup and Run Semgrep Pro

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow from the Actions tab

jobs:
  setup-and-scan:
    runs-on: ubuntu-latest # You can use macOS-latest or windows-latest if needed.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Semgrep via pip
      run: |
        python3 -m pip install semgrep

    - name: Debug Environment Variable
      run: |
        echo "SEMGREP_APP_TOKEN: $SEMGREP_APP_TOKEN"
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    - name: Install Semgrep Pro Components
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      run: |
        semgrep install-semgrep-pro

    - name: Confirm Semgrep Installation
      run: |
        semgrep --version

    - name: Run Semgrep Pro Scan
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      run: |
        semgrep --pro --config=docs/class_inheritance/pro.yaml .
