name: Setup and Run Semgrep Pro

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow from the Actions tab

jobs:
  setup-and-scan:
    runs-on: ubuntu-latest # You can use macOS-latest or windows-latest if needed.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Semgrep via pip
      run: |
        python3 -m pip install semgrep

    - name: Set up Semgrep Authentication
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      run: |
        echo "export SEMGREP_APP_TOKEN=${{ secrets.SEMGREP_APP_TOKEN }}" >> $GITHUB_ENV

    - name: Install Semgrep Pro Components
      run: |
        semgrep install-semgrep-pro

    - name: Confirm Semgrep Installation
      run: |
        semgrep --version

    - name: Run Semgrep Pro Scan
      run: |
        semgrep --pro --config=pro.yaml .
